vich_uploader:
    db_driver: orm

    #Ou doit se trouver l'image
    mappings:
        event_image:
        #dossier ou va se trouver l'image 
            uri_prefix: /images/event
        #Ou l'on souhaite envoyer les différents fichiers 
            upload_destination: '%kernel.project_dir%/public/images/event'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

