#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

# controllers:
#     resource: '../src/Controller/'
#     type:     annotation

# waza:
#     path: /waza
#     controller: App\Controller\FicheArtisteController::index